# Generated by Django 3.2.4 on 2021-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='priceplan_id',
            field=models.IntegerField(null=True),
        ),
    ]
